src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 * @Vich\Uploadable()
 */
class Property
{

    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz',
        2 => 'Fioul',
        3 => "Poêle à Bois",
        4 => "Plancher Chauffant"
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string|null
     * 
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     *  @Assert\Image(
     *  mimeTypes="image/jpeg")
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     * 
     * @var File|null
     */
    private $imageFile;

    /**
     * @Assert\Length(min=5, max=255)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $room;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedroom;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @Assert\Regex("/^[0-9]{5}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity=ImageProperty::class, mappedBy="property", cascade={"persist"})
     */
    private $imageProperties;

    public function __construct()
    {
        $this->create_at = new \DateTime();
        $this->options = new ArrayCollection();
        $this->imageProperties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }


    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }
    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRoom(): ?int
    {
        return $this->room;
    }

    public function setRoom(int $room): self
    {
        $this->room = $room;

        return $this;
    }

    public function getBedroom(): ?int
    {
        return $this->bedroom;
    }

    public function setBedroom(int $bedroom): self
    {
        $this->bedroom = $bedroom;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }

    /**
     * Get the value of imageFile
     *
     * @return  File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * Set the value of imageFile
     *
     * @param  File|null  $imageFile
     *
     * @return  Property
     */
    public function setImageFile($imageFile): Property
    {
        $this->imageFile = $imageFile;

        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    /**
     * Get the value of filename
     *
     * @return  null|String
     */
    public function getFilename(): ?String
    {
        return $this->filename;
    }

    /**
     * Set the value of filename
     *
     * @param  string|null  $filename
     *
     * @return  Property
     */
    public function setFilename($filename): Property
    {
        $this->filename = $filename;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|ImageProperty[]
     */
    public function getImageProperties(): Collection
    {
        return $this->imageProperties;
    }

    public function addImageProperty(ImageProperty $imageProperty): self
    {
        if (!$this->imageProperties->contains($imageProperty)) {
            $this->imageProperties[] = $imageProperty;
            $imageProperty->setProperty($this);
        }

        return $this;
    }

    public function removeImageProperty(ImageProperty $imageProperty): self
    {
        if ($this->imageProperties->contains($imageProperty)) {
            $this->imageProperties->removeElement($imageProperty);
            // set the owning side to null (unless already changed)
            if ($imageProperty->getProperty() === $this) {
                $imageProperty->setProperty(null);
            }
        }

        return $this;
    }
}

templates/browse/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}

<div class="jumbotron text-center">
    <div class="row">
        <div class="col-sm-8">
        <p>L’agence NathDie Immobilier vous accompagne sur l’ensemble de vos projets immobiliers en mettant à votre disposition une équipe de professionnels compétents. 
        Membre du groupement d'agences Imagimmo nous intervenons sur la location, la gestion locative 
        (Garantie Loyers Impayés, détériorations Immobilières et protection juridique) et la transaction en assurant un service de qualité personnalisé basé sur la 
        confiance et le respect.</p>
        <p> Nous vous accueillons du lundi au vendredi de 9h à 12h et de 14h à 18h. Bonne visite ! L’équipe de NathDie Immobilier.</p>
        
        </div>
        <div class="col-sm-4">
        <p> NathDie Immobilier</p>
        <p> 50 route du moulin </p>
        <p> 59230 Saint Amand Les Eaux </p>
        <p> Tél : 04.55.48.57.21 </p>
        <p> Email : contact@nathdie.ue </p>
        </div>
    </div>
</div>

<div class="container">
<h2> Les derniers biens </h2>
    <div class="row flex">
    {% for property in properties %}
        <div class="col-3">
            <div class="card">
                            {% if property.filename %}
                    <img src="images/properties/{{ property.filename }}" alt="card-img-top" style="width:100%; height:auto;">

                    {% else %}
                    <img src="images/properties/empty.jpg" alt="card-img-top" style="width:100%; height:auto;">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{{path('property.show', {id: property.id, slug:property.slug})}}">{{property.title}}</a>
                    </h5>
                        <p class="card-text">
                        {{property.city}} ({{property.postalCode}})
                        </p>
                    <div class="text-primary"> {{ property.price | number_format(0, '', ' ') }} €</div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>

{% endblock %}

templates/browse/property.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tous nos biens{% endblock %}

{% block body %}
<div class="jumbotron">
    <div class="container">
        {{ form_start(form)}}
        <div class="form-row">
            <div class="col">
                {{ form_row(form.minSurface)}}
            </div>
            <div class="col">
                {{ form_row(form.maxPrice)}}
            </div>
            <div class="col">
                {{ form_row(form.options)}}
            </div>
            <div class="col">
                <button class="btn btn-primary"> Rechercher </button>
            </div>
        </div>
         {{ form_end(form)}}
    </div>
</div>
<div class="container mt-4">
<h1> Tous nos biens </h1>
    <div class="row">
        {% for property in properties %}
        <div class="col-md-4 mb-3">
            <div class="card">
                {% if property.filename %}
                    <img src="images/properties/{{ property.filename }}" alt="card-img-top" style="width:100%; height:auto;">

                    {% else %}
                    <img src="images/properties/empty.jpg" alt="card-img-top" style="width:100%; height:auto;">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{{path('property.show', {id: property.id, slug:property.slug})}}">{{property.title}}</a>
                    </h5>
                    <p class="card-text">{{ property.description | nl2br }}</p>
                    <p class="card-text">{{property.surface}} m² - {{property.city}} ({{property.postalCode}})</p>
                    <div class="text-primary" style="font-size:2rem;font-weight:bold;"> {{ property.price | number_format(0, '', ' ') }} €</div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="pagination mt-4">
    {{ knp_pagination_render(properties)}}
    </div>
</div>

{% endblock %}

templates/browse/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}

{% block body %}
<div class="jumbotron">
    <div class="container">
    {% for message in app.flashes('success') %}
    <div class="alert alert-success">
    {{ message }}
    </div>
    {% endfor %}
        {% if not form.vars.valid %}
    <div class="alert alert-danger">
        Vous avez fait une erreur dans le formulaire
    </div>
    {% endif %}

        <div class="row">
            <div class="col-md-8">
                <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            {% if property.filename %}
                            <img src="../images/properties/{{ property.filename }}" alt="card-img-top" style="width:100%; height:auto;">
                            {% else %}
                            <img src="../images/properties/empty.jpg" alt="card-img-top" style="width:100%; height:auto;">
                            {% endif %}
                        </div>
                        {% for image in property.imageProperties %}
                            {% if image  %}
                            <div class="carousel-item">
                                <img src="../images/{{ image.filename }}" alt="" style="width:100%; height:auto;">
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <h1> {{ property.title }} </h1>
                <h2> {{ property.room }} pièces - {{ property.surface}} m² <h2>
                {% if property.sold == false %}
                    <div class="text-primary" style="font-size:2rem;font-weight:bold;"> {{ property.price | number_format(0, '', ' ') }} €</div>
                    <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#modalContactForm"> Contacter l'agence </a>     
                {% else %}
                    <div class="text-primary mt-4" style="font-size:2rem;font-weight:bold;"> Ce bien a été vendu </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container mt-4 mb-3">
    <p class="mb-4"> {{ property.description | nl2br }} </p>
    <div class="row mt-2">
        <div class="col-md-8">
        <h2> Caractéristiques </h2>
            <table class="table table-striped">
            <tr>
                <td> Surface habitable </td>
                <td> {{ property.surface }} m² </td>
            </tr>
            <tr>
                <td> Pièces </td>
                <td> {{ property.room }} </td>
            </tr>
            <tr>
                <td> Chambres </td>
                <td> {{ property.bedroom }} </td>
            </tr>
            <tr>
                <td> Etage </td>
                <td> {{ property.floor }} </td>
            </tr>
            <tr>
                <td> Chauffages </td>
                <td> {{ property.heatType }} </td>
            </tr>
            </table>
        </div>
        <div class="col-md-4">
        <h2> Options  </h2>
        <ul class="list-group">
            {% for option in property.options %}
            <li class="list-group-item"> {{option.name}}</li>
            {% endfor %}
        </ul>
        <h2 class="mt-4"> Adresse </h2>
        <p> {{property.adress}}</p>
        <p> {{property.city}}, {{property.postalCode}}  </p>
        </div>
    </div>


</div>

                <div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Contact</h4>
        {{ form_start(form) }}
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <div class="md-form mb-2">
        {{form_row(form.firstname) }}
        </div>
        <div class="md-form mb-2">
        {{form_row(form.lastname) }}
        </div>
        <div class="md-form mb-2">
        {{form_row(form.phone) }}
        </div>
        <div class="md-form mb-2">
        {{form_row(form.email) }}
        </div>
        <div class="md-form mb-2">
        {{form_row(form.message) }}
        </div>
      </div>
      <div class="modal-footer d-flex justify-content-center">
        <button class="btn btn-default">Envoyer</button>
      </div>
      {{ form_end(form) }}
    </div>
  </div>
</div>

{% endblock %}